### ISSUE TITLE
 I want to run model on my own dataset, but I don't know how to organize my dataset.

### ISSUE THREAD

**Issue by JQJ001** [zhou13/lcnn#1]
Hello, Thanks for sharing. I want to run model on my own dataset, but I don't know how to organize my dataset.
 Firstly, I downloaded the pre-processed dataset from Google Drive, its size is about 8.1G. 
You said that the wireframe.py is the script for pre-processing the Wireframe dataset to npz, but I couldn't find the necessary .json files from the pre-processed dataset,  so I failed to run  wireframe.py.  I want to know that do you have the raw dataset with .json files,  from which I can learn to organize my own dataset.
Thanks.

**Comment by zhou13** [comment]
You should be able to find it in the google drive.  README.md is updated accordingly.

**Comment by JQJ001** [comment]
OK, thanks.
