### ISSUE TITLE
Training on CPU

### ISSUE THREAD

**Issue by Arktius** [zhou13/lcnn#10]
Hi zhou13, I've just donwloaded your repo and wanted to execute the main.py script, but I don't have a NVIDIA GPU. How can I use the CPU instead? I'm aware of the fact that training on a CPU will take X-times longer. I'd like to understand the application first.

Thanks in advance! =)

**Comment by zhou13** [comment]
I think that is possible. Just run
````
python ./train.py -d "" --identifier baseline  config/wireframe.yaml
````
and it should work I guess.

**Comment by zhou13** [comment]
Let me know if you have additional questions.
