### ISSUE TITLE
lines or juncs to wireframe

### ISSUE THREAD

**Issue by shinexunju** [zhou13/lcnn#12]
Hi,

With process.py script, how to derive wireframe or contour? 

btw, during evaluation, ```K``` could be 0, which will raise runtime error.
https://github.com/zhou13/lcnn/blob/0082f1738c7ef814d8fbb14dde72d187cfe54353/lcnn/models/line_vectorizer.py#L168

Thanks and the results looks great!

**Comment by zhou13** [comment]
Hi @shinexunju , sorry for the late reply.  Hope that you have already find the solution. You can refer to https://github.com/zhou13/lcnn/blob/0082f1738c7ef814d8fbb14dde72d187cfe54353/process.py#L118 as an example to extract the wireframe.

Also, Thanks for pointing out of the bug! I will fix it.

**Comment by shinexunju** [comment]
Thanks for your reply! But based on my test, I think ```(a[1], a[0]), (b[1], b[0])``` are just the two endpoints of a line.

How to determine which four lines or juncs to form a wireframe instead of enumerating?  Thanks!

**Comment by zhou13** [comment]
I am not sure what you mean by "forming a wireframe". If you want to know the connectivity of wireframe, you need to convert the endpoints into the vertices of a graph and lines into the edges. You can then process the graph using graph algorithms. Assuming you want to find a rectangle, you can then a BFS on it. However, current LCNN is not designed for finding rectangular surfaces. The quality may or may not be satisfiable.
