### ISSUE TITLE
About mean and stddev in the code

### ISSUE THREAD

**Issue by ningding-o** [zhou13/lcnn#14]
老哥，config文件夹里wireframe.yaml里面有两行代码mean: [109.730, 103.832, 98.681]，stddev: [22.275, 22.124, 23.229]，请问这个是wireframe数据集的均值何方差吗？ 我自己算的均值是[137.36, 126.51, 116.05]， 请问这个均值方差是那个数据的数据呀？

**Comment by zhou13** [comment]
The mean and stddev are from a synthetic dataset. Since the network is full of batch normalization layers, the input normalization is not that important.
