### ISSUE TITLE
Mac crashes when running on basic image

### ISSUE THREAD

**Issue by vlall** [zhou13/lcnn#16]
Thanks for posting this code! I'm using all of the default settings, and have everything installed correctly, but the `demo.py` crashes mid-execution, and then crashes my computer (OS X 10.14.6). I'm not using a local machine with a GPU unfortunately, just a 3.1 GHz i7 CPU. Any tips for making changes to my config? I'm using the pre-trained model provided. Thank you.

**Comment by zhou13** [comment]
Please provide more details about your crash, e.g., your image, command, and a backtrace maybe?

**Comment by zhou13** [comment]
Feel free to reopen this issue when you have updates.
