### ISSUE TITLE
Validation crashes with KeyError when training from scratch

### ISSUE THREAD

**Issue by javierjsa** [zhou13/lcnn#17]
Hi,
I'm trying to train a model from scratch using the default configuration with the provided dataset. In other words, just trying to reproduce the training process before moving on to using my own dataset.

Trains starts ok but crashes on validation:

`Running validation...                                                                            Traceback (most recent call last):
  File "train.py", line 182, in <module>
    main()
  File "train.py", line 174, in main
    trainer.train()
  File "/home/jsaez/Repositorios/Otros/lcnn/lcnn/trainer.py", line 290, in train
    self.train_epoch()
  File "/home/jsaez/Repositorios/Otros/lcnn/lcnn/trainer.py", line 202, in train_epoch
    self.validate()
  File "/home/jsaez/Repositorios/Otros/lcnn/lcnn/trainer.py", line 123, in validate
    total_loss += self._loss(result)
  File "/home/jsaez/Repositorios/Otros/lcnn/lcnn/trainer.py", line 70, in _loss
    losses = result["losses"]
KeyError: 'losses'
`

The only available keys in result are **feature** and **preds**

However, this does not happen if I provide a checkpoint to resumen training from in wireframe.yaml (the provided trained model renamed as checkpoint_latest.pth.tar), as in this case 'losses' key exists. **Correction**: it also happens, but after several train/validation cycles.

I am using a Python 3.6 pip environment in Ubuntu 16.04 with cuda 10.0. These are some the package versions I have installed:
torch==1.1.0
torchvision==0.3.0
PyYAML==3.13
scikit-image==0.16.2
docopt==0.6.2
opencv-python==4.1.2.30

**Update:** I've tried the same with a Conda environment, created following the instructions in the readme.md and got the same outcome

**Comment by zhou13** [comment]
Sorry, that was a bug introduced recently. I just added some fixes. Please test again.

**Comment by javierjsa** [comment]
Hi,
I've training a model for a few hours without issues. Thank you so much.

**Comment by zhou13** [comment]
Great! Free feel to reopen this bug if you still have trouble training models.
