### ISSUE TITLE
How to obtain 3D wireframe

### ISSUE THREAD

**Issue by ayyappa-swamy** [zhou13/lcnn#18]
Hi @zhou13 ,
Thanks for sharing your code here. We are able to reproduce the results of 2D wireframes using **lcnn** as well as **wireframe**.
However we are not able to reproduce the results of [**Learning to Reconstruct 3D Manhattan Wireframes from a Single Image**](https://arxiv.org/abs/1905.07482) that can give 3D wireframe.
Do you have an implementation of it ?

**Comment by zhou13** [comment]
Hi @ayyappa-swamy , thanks for being interesting in our project. We will release the code and updates of 3D wireframe project soon. Some metrics and code of that project need to be cleaned up so others can run and test it. I will close this issue as it is not related to this repository.
