### ISSUE TITLE
Inquire the meaning of data 

### ISSUE THREAD

**Issue by yangengt123** [zhou13/lcnn#2]
Hi, 
Thanks for sharing the code of your great work. 

I am trying to run the code to get a better insight of your paper, but I get confused about the variable meanings in the input_dict. In the dict, I assume
 lmap:  line heatmap, but may I ask what the float value means? I thought it should be binary 
 jmap:  junction heatmap
 joff:     junction offset map,

but I cannot understand what junc, Lpos,  Lneg ,  lpos, and  lneg  are. Especially, I found the the shape of  Lpos, Lneg is  n\*2, while lpos and lneg has a shape n\*2\*3. 

Could you offer more explanation about them? 

Thanks in advance!

**Comment by zhou13** [comment]
See `dataset/wireframe.py` to understand the details about data pre-processing.

**Comment by yangengt123** [comment]
> See `dataset/wireframe.py` to understand the details about data pre-processing.

Thanks for the quick reply. 
Which part are you indicating in ```dataset/wireframe.py```? Actually, I have read both this file and the .json in raw data .tar, but I did not get any cue about the physical meaning of them.

**Comment by zhou13** [comment]
> lmap: line heatmap, but may I ask what the float value means? I thought it should be binary

https://github.com/zhou13/lcnn/blob/36f172d7d5965b5d7893cf1e7556edeb8a3d00c4/dataset/wireframe.py#L92

> which part are you indicating in `dataset/wireframe.py`?

https://github.com/zhou13/lcnn/blob/36f172d7d5965b5d7893cf1e7556edeb8a3d00c4/dataset/wireframe.py#L99-L103

**Comment by zhou13** [comment]
I add more comments to `dataset/wireframe.py` and `lcnn/datasets.py` to explain the meaning of each variable you asked.  Hopefully, it is more clear now.

**Comment by yangengt123** [comment]
Thanks. It helps.   
BTW may I ask if there is any implementation for test on image data only? 
I plan to perform test on the my own dataset, which contains only the RGB image. I found the code for test (```process.py```) seems still need ```meta``` data to run. I am trying to modify the code for my test, but it will be perfect if there is any existing test code.

**Comment by zhou13** [comment]
Not yet as I am busy with a paper submission. You are more than welcome to contribute that if you finish it :)

**Comment by sachinkaundal** [comment]
@zhou13, can you please tell what kind of data train.json and valid.json consist of that you shared with dataset and how you generated. Thanks in advance for response.

**Comment by zhou13** [comment]
@sachinkaundal Not sure what kind of answer you need. The code at `lcnn/dataset.py` should explain your question well.

**Comment by sachinkaundal** [comment]
@zhou13 Thanks for the response. i am not able to understand train.json and valid.json(shared with wireframe_raw) files that are used during processing(wireframe.py). Even i read wireframe.py file i am not getting any cue about these files. 
Thanks

**Comment by zhou13** [comment]
You might want to see this repo for the dataset: https://github.com/huangkuns/wireframe.

**Comment by sachinkaundal** [comment]
@zhou13, Thank you so much for your time.

**Comment by SEUZTh** [comment]
Hello, I have downloaded the dataset from Onedrive. It seems that the dataset's directory structure in Onedrive is different from that in the compressed package. Could you share the directory structure with me? I'm looking forward to your reply.
