### ISSUE TITLE
Could you check checkpoint on Google Drive?

### ISSUE THREAD

**Issue by koji** [zhou13/lcnn#21]
![Screen Shot 2020-02-12 at 9 09 33 PM](https://user-images.githubusercontent.com/474225/74394995-1fce9e80-4ddc-11ea-8f4d-8ee7a969c13e.png)

```bash
$ tar -xvf 190418-201834-f8934c6-lr4d10-312k.pth.tar
tar: Error opening archive: Unrecognized archive format
```

cannot uncompress the checkpoint.

Thanks!

**Comment by zhou13** [comment]
Please read the README carefully. You are not suppose to uncompress it.
