### ISSUE TITLE
while i use my train data of size 1024x1024 ,the result is bad

### ISSUE THREAD

**Issue by xuyuhui666** [zhou13/lcnn#25]
thanks your codes!
but while  i use my train data of size 1024x1024 ,the result is bad.Is there a good way to train data with different image sizes  and different rotation angles

**Comment by zhou13** [comment]
Currently this project uses hyperparamters that were tuned for 512x512.  It was also trained on that resolution. It is expected that you will get bad result with higher resolution.  For it to work on 1024 x 1024, you could first try training on that resolution.

**Comment by xuyuhui666** [comment]
Thanks for your reply
i create my train date of size 1024x1024 by running the wireframe.py ,and train on the resolution ,but i test my image by running the demo.py on the same resolution of image,the result is bad.and the results of visualization in the logs/200303-130709-65ac416-baseline/viz/  are also not good

**Comment by zhou13** [comment]
Then you need to keep tuning the network until `viz` looks good :)

**Comment by xuyuhui666** [comment]
the result is good by using the data of size 512x512,but while i generate the train data of size 1024x1024 and set the heatmap_scale=(256,256) in the wireframe.py,the sum loss is not going down,the model does not converge,has you any suggestions about it,thanks

**Comment by zhou13** [comment]
It is likely there are some bugs in your code. There are too many things that can go wrong. When you increase the resolution, the receptive field become smaller, so the network might need a overhaul. The positive/negative sample ratio of junctions also changes, which brings challenges to training. Also most existing backbone networks are tuned on resolution 64-128. Increasing the resolution on this task is far more complex than just bumping the number.

**Comment by xuyuhui666** [comment]
It's seem there are many sense that use the different size images,while i use the size 512 , the line can not clear to detect in image,so i have to use the 1024 size ,can you help me  to alter your codes for using the different images?
in fact ,i want to use your code to detect the table line in document,the size of picture is very large ,while resize the image to 512,the line can't be seen clearly
thanks for your help!

**Comment by xuyuhui666** [comment]
in fact,you need not alter your code by yourself,you can tell me how and where to alter
respect for your reply,thx!

**Comment by zhou13** [comment]
Sorry, I do not have the bandwidth to support your project.
