### ISSUE TITLE
line_vectorizer “out  of memory”

### ISSUE THREAD

**Issue by renbingdong** [zhou13/lcnn#28]
HI :  
   I had an "out of memory" error  while trying to run the code. After debugging, I found the problem in the "forward" method of the "lcnn/models/line_vectorizer.py". 

    `      
           # xp: [N_LINE, N_CHANNEL, N_POINT]
            xp = (
                (
                    x[i, :, px0l, py0l] * (px1 - px) * (py1 - py)
                    + x[i, :, px1l, py0l] * (px - px0) * (py1 - py)
                    + x[i, :, px0l, py1l] * (px1 - px) * (py - py0)
                    + x[i, :, px1l, py1l] * (px - px0) * (py - py0)
                )
                .reshape(n_channel, -1, M.n_pts0)
                .permute(1, 0, 2)
            )
          #  x.size:  (-1, 128, 128, 128)
          #  px0l、px1、px、py0l、py1、py  size：（1435200）
    `
The operation takes up more than 2G memory, and takes up more GPUs.  How do I optimize this operation? 

PS： I want to run it on a limited GPU to improve GPU utilization

Thanks!

**Comment by zhou13** [comment]
The default parameters are set for a GPU with 12 GB onboard memory. If your GPU have less memory, try decreasing the batch size.
