### ISSUE TITLE
TensorBoard caught SIGTERM; exiting...

### ISSUE THREAD

**Issue by jwngo** [zhou13/lcnn#29]
Hi Yichao, 

Thanks for sharing your code! 

While training the model, I get the following error

`TensorBoard caught SIGTERM; exiting...
`

I have tried training another model from scratch as well, so now I have two models but both of them would stop running at the same iteration; 
`023/0480k `, which is not enough to reproduce the pre-trained model of 000312000 in logs/*/npz (only saved up to 000160000)

Do you have any idea what is causing this error? I tried googling to no avail. 

Thank you Yichao.

**Comment by jwngo** [comment]
So i noticed that

**Comment by jwngo** [comment]
So I think that it is due to the max_epoch being 24, a very simple thing that I missed.....

Testing it right now.

**Comment by sachinkaundal** [comment]
@jwngo, can you please tell what would be max_epoch size to train model(successful)?

**Comment by zhou13** [comment]
@sachinkaundal You can use any value you want. After reaching `max_epoch`, `tensorboard` will just automatically close.

**Comment by sachinkaundal** [comment]
@zhou13  thank you for your response, Before reaching `max_epoch`, i am getting above message
(suppose, max_epoch=20, when it reaches 19 ) 
> "TensorBoard caught SIGTERM; exiting..."

**Comment by zhou13** [comment]
Why is that not expected?

**Comment by sachinkaundal** [comment]
@zhou13, means this is the final response we will get at the end of training or something else.
If yes, then i am getting only logs in /logs directory but not checkpoints which are required for testing. Thanks for response in advance..
./process.py config/wireframe.yaml <path-to-checkpoint.pth> data/wireframe logs/pretrained-model/npz/000312000

**Comment by zhou13** [comment]
I don't really understand your question but you might want to adjust `io.validation_interval` in the setting.
