### ISSUE TITLE
How to implement this work in real-world robotic navigation?

### ISSUE THREAD

**Issue by weijiafeng** [zhou13/lcnn#3]
Hi @zhou13 ,

I've looked into this work after listening to Professor Ma's talk on 3D reconstruction. Thank you for sharing the codes of this work. 

I am wondering what are the steps to implement this on cameras, with my end-goal being extracting the spatial coordinates of a certain object in the 3D reconstructed view? 
  1) Do I need to pretrain this model with my own datasets of the images in my environment where the robot is navigating? 
  2) Is it real-time SLAM after the pretraining step?

Many thanks in advance!

**Comment by zhou13** [comment]
Hi @weijiafeng ,

This project is about wireframe extraction and line detection from single image. It is irrelevant to SLAM for now. It is possible to combine it with https://github.com/tum-vision/lsd_slam or https://github.com/manhofer/Line3Dpp to get semantic wireframes with SLAM, but that still requires some extra work and research.

Regards your questions,

1. pretraining on your environment always gives you better performance, but it is not mandatory.
2. Real-time is more about engineering. LCNN is not real-time out-of-the-box but it should not be hard to achieve that if you want to.

Yichao Zhou

**Comment by zhou13** [comment]
I will close this issue and you are welcome to ask additional questions.
