### ISSUE TITLE
Download Exceed Quota for Dataset

### ISSUE THREAD

**Issue by fcr3** [zhou13/lcnn#30]
Hi I was just wondering if I could somehow download the wireframe dataset in another way besides google drive? It seems like the download quota has already been exceeded.

Thanks!
Christian

**Comment by zhou13** [comment]
Sorry, we currently do not have access to a dedicated server with large storage. I think the quota of google drive is reset daily. In case of download quota being exceeded, one can try downloading `wireframe_raw.tar.xz` and processing it accordingly.
