### ISSUE TITLE
Support pytorch 0.4

### ISSUE THREAD

**Issue by HC-2016** [zhou13/lcnn#32]
Thanks for your great codebase.
Does it support for  pytorch 0.4?

**Comment by zhou13** [comment]
I haven't tested it on 0.4, but I guess it should work. If there is error, feel free to reopen and let me know. Latest pytorch is always prefer.

**Comment by HC-2016** [comment]
I have tried  pytorch 0.4.0 but there are some funcs supported in version >= 0.4.1 .......
