### ISSUE TITLE
alternative for image processing by cv2?

### ISSUE THREAD

**Issue by hua-wu-que** [zhou13/lcnn#36]
Hi!

I notice in the validation code, there are some place save images using first calling imshow(), then use plt.savefig(). Above process could be achieved by using cv2.imwrite. I wonder if this is just some random choice or is there some difference between using matplotlib and cv2?  Thank you!

I realize the imshow func contains some customized routines like plot the color bars, now it makes much more sense to me. Is this the reason for using plt?

**Comment by zhou13** [comment]
Just like what you said, matplotlib has more functionality.
