### ISSUE TITLE
What is the "f" that is concatenated to the line feature vector x?

### ISSUE THREAD

**Issue by TangXiaoyu9** [zhou13/lcnn#42]
Hi, I am trying to extract lcnn line features given the line segments detected by lsd, but I am stuck here:

https://github.com/zhou13/lcnn/blob/290b457ec54f2aeb8e7de88c6837747ebc5aa168/lcnn/models/line_vectorizer.py#L95
**x** seems to be the feature vector, after the max-pooling, you concatenate the **x** and **f** before the fully connected layer. What is the **f** here?

In my modification, the size of **x** equals to the number of lsd lines, which is different from the size of **f**. Any suggestions on how to modify the **f**?

**Comment by zhou13** [comment]
`f` is represents hardcoded feature. By default, it is just a zero vector.
