### ISSUE TITLE
infer too slow

### ISSUE THREAD

**Issue by M-crazy** [zhou13/lcnn#43]
效果很好，但是好慢好慢，GPU测试图均耗时3s左右，难以工业落地。

**Comment by zhou13** [comment]
The inference speed of LCNN is 12 images per sec on a 1080Ti. There're other following up works that address the issues on efficiency.

**Comment by lucy3589** [comment]
> 效果很好，但是好慢好慢，GPU测试图均耗时3s左右，难以工业落地。

请你关于这个问题，您最后怎么解决的呢？

**Comment by lucy3589** [comment]
> The inference speed of LCNN is 12 images per sec on a 1080Ti. There're other following up works that address the issues on efficiency.

inference speed is containt pre_process_time and post_process_time?  And you speed up wireframe detection alg?

**Comment by guker** [comment]
> > The inference speed of LCNN is 12 images per sec on a 1080Ti. There're other following up works that address the issues on efficiency.
> 
> inference speed is containt pre_process_time and post_process_time? And you speed up wireframe detection alg?

same question for you @zhou13

**Comment by zhou13** [comment]
It has been a long time since I worked on this project so I might be wrong, but I think 12 im/sec in the network time excluding pre/post_processing.
