### ISSUE TITLE
pretrained model broken！

### ISSUE THREAD

**Issue by Jsooooooo** [zhou13/lcnn#44]
下载文件解压不了，已损坏

**Comment by Jsooooooo** [comment]
i see

**Comment by quant-kenny** [comment]
@Jsooooooo Hello my friend,

Were you able to decompress the pretrained model? I am trying as well, but am not able to decompress it with the error:
"Invalid archive header" 

Please let me know if/how you solved this!

**Comment by kenjiflores** [comment]
@Jsooooooo  Hello my friend,

Were you able to decompress the pretrained model? I am trying as well, but am not able to decompress it with the error:
"Invalid archive header"

Please let me know if/how you solved this!
@zhou13

**Comment by Jsooooooo** [comment]
decompress in linux, maybe

**Comment by Jsooooooo** [comment]
> @Jsooooooo Hello my friend,
> 
> Were you able to decompress the pretrained model? I am trying as well, but am not able to decompress it with the error:
> "Invalid archive header"
> 
> Please let me know if/how you solved this!
> @zhou13

decompress in linux, maybe

**Comment by zhou13** [comment]
You do not need to decompress the file. The pre-trained model is not compressed...
