### ISSUE TITLE
i want train rectangle

### ISSUE THREAD

**Issue by carlsummer** [zhou13/lcnn#49]
size is 512*512 ，I want train size is 128*512，how i do for？

**Comment by carlsummer** [comment]
File "/home/zengxh/workspace/lcnn/lcnn/models/line_vectorizer.py", line 189, in sample_lines
    match[t, jtyp[match[t]] != t] = N
RuntimeError: CUDA error: device-side assert triggered

**Comment by zhou13** [comment]
I won't provide support for any modification of the repo.
