### ISSUE TITLE
predict error

### ISSUE THREAD

**Issue by carlsummer** [zhou13/lcnn#52]
为什么训练完预测
同样的图片
不同的batch_size 结果不一样
````
inputs = torch.cat(self.images)
images = inputs.to(self.device).half()
batchs = 8
with torch.no_grad():
    input_dict = {
        "image": images[:batchs],
        "meta": [
            {
                "junc": torch.zeros(1, 2).to(self.device).half(),
                "jtyp": torch.zeros(1, dtype=torch.uint8).to(self.device).half(),
                "Lpos": torch.zeros(2, 2, dtype=torch.uint8).to(self.device).half(),
            }
            for _ in range(batchs)
        ],
    }
    H = self.model(input_dict)["preds"]
    G = H["lines"][6]
````

batchs=7 或者8 或者10
得到的G 结果不一样

**Comment by carlsummer** [comment]
![image](https://user-images.githubusercontent.com/16281965/129719955-ab605c24-7080-44b7-ac42-68eeb7633521.png)

**Comment by carlsummer** [comment]
![image](https://user-images.githubusercontent.com/16281965/129720009-0bbfc879-738d-4676-a871-fbf3d8dc9433.png)

**Comment by zhou13** [comment]
What is `G`?

**Comment by zhou13** [comment]
Are you sure you can reproduce this problem on the original repo? It seems you are using a heavily modified repo. Did you do `model.eval()`?

**Comment by carlsummer** [comment]
yes ，I use model.eval()  ,but,I now find that although his results have changed, it does not affect the final coordinate value, which is similar to float32 and float64, but affects the latter few.
I checked the information and found that it was a torch bug

**Comment by zhou13** [comment]
Thanks for the update.
