### ISSUE TITLE
Can I ask you a question? There is a line of code that I don't understand, can you explain this line of code ？

### ISSUE THREAD

**Issue by tanpengjie** [zhou13/lcnn#55]
https://github.com/zhou13/lcnn/blob/290b457ec54f2aeb8e7de88c6837747ebc5aa168/lcnn/models/line_vectorizer.py#L80

Hi. Thanks for sharing your great code.
In order to extract the features of line segments, you proposed LOI Pooling. I think this idea is very good. My understanding of LOI Pooling is to divide any line segments into 32 points, and use 32 points to represent line segment. But I can't understand this line of code, can you help explain it?

**Comment by zhou13** [comment]
This is bilinear sampling.
