### ISSUE TITLE
环境搭建

### ISSUE THREAD

**Issue by 1369841815** [zhou13/lcnn#57]
您好，我按照您的方法搭建环境后，然后用pycharm运行出现了一系列问题，用代码搭建也一样，是不是使用的环境的版本有区别呀，希望能得到您的帮助
![mmexport1647704047416](https://user-images.githubusercontent.com/97372752/159127722-f7865097-b0cd-4cb2-9252-3862eb817a59.png)
![mmexport1647704044584](https://user-images.githubusercontent.com/97372752/159127736-86524d20-4a7f-4404-87f2-5cb89d82ef9f.png)
![Uploading mmexport1647704049652.png…]()

**Comment by zhou13** [comment]
Sorry but I am not familiar with pycharm.

**Comment by 1369841815** [comment]
我在终端运行代码后，提示这样的错误，请问这个有影响吗
![Uploading mmexport1647750760925.png…]()
