### ISSUE TITLE
Questions about the training process

### ISSUE THREAD

**Issue by hyylx94** [zhou13/lcnn#58]
Hi, 

Thanks for this nice work. I'm training to train the network using my own dataset and I have a few questions:
1. In the config file "wireframe.yaml", the validation interval is set to 24000. If I understand correctly, this means that validation is run every 24000 times of iteration. Can I know the reason for this number? And why not run validation every epoch?
2. I don't fully understand the loss part. What is the loss function for the network? Is it the weighted sum of jmap, lpos, lneg...?

Thanks in advance!

Kind regards,
Xin

**Comment by zhou13** [comment]
1. You can change it to whatever you want. It just might be too slow if you set it to 1...
2. It is a weighted sum as you said.
