### ISSUE TITLE
model file broken

### ISSUE THREAD

**Issue by billhyde** [zhou13/lcnn#6]
Hi, Thanks for sharing.
I download your model file,but it seems that the file is borken, i don't know why.
![image](https://user-images.githubusercontent.com/17793530/62187842-39a71780-b39d-11e9-9d00-a863d1e1adfe.png)

**Comment by zhou13** [comment]
It was not supposed to be opened by an archiver. Use `train.py` or `process.py` to run the model.

**Comment by billhyde** [comment]
ok,thanks~
