### ISSUE TITLE
Does the dataset set have requirements for picture size？

### ISSUE THREAD

**Issue by fxt960803** [zhou13/lcnn#62]
Hello ，I want to ask you about make my own dataset , the image resolution is 3072 * 3072、3072 * 4096，I should set my own size or use yours？Does the data set have requirements for picture size？
Then， How did this happen:
global /io/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('data/LNTUframe_raw/images/lntu12'): can't open/read file: check file path/integrity
Thanks！
I look forward to your reply!

**Comment by zhou13** [comment]
I don't provide support for 3rd applications.
