### ISSUE TITLE
How to avoid thaht the resulting image has an decreased resolution.

### ISSUE THREAD

**Issue by zaki-star** [zhou13/lcnn#63]
Hello,

I applied the pretrained model on my own images. It works very well. But I realised that the resulting image (output) has an other resolution than the original image (input). 
I want to keep the orginal image size. How can I do that?

Thank you in advance.

**Comment by zhou13** [comment]
The output image is for debugging/visualization purposes only.

**Comment by zaki-star** [comment]
Okay thank you. 
To answer my question by myself: The output image has the original resolution. But when the image is saved from the matplotlib window then the resolution of the saved image will be decreased. Sorry for the confusion I haven't recognized this from the beginning.
