### ISSUE TITLE
Link to pretrained model is not working

### ISSUE THREAD

**Issue by TinaLiuArcher** [zhou13/lcnn#66]
Hi, 

The link to the pretrained model is not working. The error is below. Would you help to fix it? Thanks!

"Sorry, you can't view or download this file at this time.
Too many users have viewed or downloaded this file recently. Please try accessing the file again later. If the file you are trying to access is particularly large or is shared with many people, it may take up to 24 hours to be able to view or download the file. If you still can't access a file after 24 hours, contact your domain administrator."

**Comment by zhou13** [comment]
Unfortunately, there is a download limitation from google drive. You have to wait for 24 and retry. We currently don't have the capability to host our data on a more reliable server.

**Comment by TinaLiuArcher** [comment]
Sure, thanks for the reply!
