### ISSUE TITLE
question about loss

### ISSUE THREAD

**Issue by HC-2016** [zhou13/lcnn#67]
1. What's the meaning of "lmap"? It seems to contibute to the loss but I can not find in the paper
https://github.com/zhou13/lcnn/blob/57524636bc4614a32beac1af3b31f66ded2122ae/lcnn/models/multitask_learner.py#L76

2. In the paper, "We use l2 regression to predict the offset map O".
But it seems to use l1 loss in the code.
https://github.com/zhou13/lcnn/blob/57524636bc4614a32beac1af3b31f66ded2122ae/lcnn/models/multitask_learner.py#L82

**Comment by zhou13** [comment]
`lmap` is line heatmap. It is some legacy stuff from previous work. I heard some reports that removing it will increase the performance. Therefore, It is safe to remove it or ignore it.
