### ISSUE TITLE
mismatch visual and numerical results

### ISSUE THREAD

**Issue by xavierfay** [zhou13/lcnn#70]
Hi, First of all, thanks for the structured code!

I am training the model on my own dataset. Although the results of the validation run  (shown below) seem promising, the vecl images in the viz folder almost show no lines. The plotted junctions do have good visual results. How can I increase the number lines outputted by the model and plotted in the vecl_b image? Increasing the sampler of the line output in the config file does not work. The number of lines outputted by the `sample_lines` function in` line_vectorizer.py` is sufficient. 

progress | sum    | jmap   | lmap   | joff   | lpos   | lneg   | speed
008/0014k| 0.07836| 0.00611| 0.00097| 0.02606| 0.04188| 0.00334 

Thank you in advance!

**Comment by zhou13** [comment]
Sorry I don't provide support for 3rd application.
