### ISSUE TITLE
Size of PTH file?

### ISSUE THREAD

**Issue by I1234567R** [zhou13/lcnn#71]
Thank you for this repository it's greatly appreciated! The example pth file provided on Google Drive is 152,753 KB compared with the same data trained locally at 153,159 KB. Has anything changed since that model was trained that would cause this increase? I need to be able to train on my custom dataset and produce exactly the same model file as the example. Currently, I get the larger of the two files even with the example dataset.

Any help/information is greatly appreciated.

**Comment by zhou13** [comment]
I think it is might be due to the difference in pytorch version.

**Comment by I1234567R** [comment]
Do you know what the exact version of pytorch was used? I've followed the instructions however this installs the latest version.

**Comment by zhou13** [comment]
Unfortunately, I don't have the record. I generally won't suggest this but If you need the exact file size, you may try the pytorch version release when the repo was created.

**Comment by I1234567R** [comment]
Thank you for the advice, this was the problem! Also, have you written anything to convert the pth models to pt or onnx so they can be run in another language, ideally C++?

**Comment by zhou13** [comment]
I haven't worked on deployment of this project.
