### ISSUE TITLE
tar archive error with pretrained models

### ISSUE THREAD

**Issue by surya-1729** [zhou13/lcnn#76]
Hello,

I am trying to extract the files from tar file from Google drive https://drive.google.com/file/d/1NvZkEqWNUBAfuhFPNGiCItjy4iU0UOy2/edit. This file when downloaded, has issues with extraction. This tar looks broken.

**Comment by aruscha-k** [comment]
Hello, running into the same problem! Would be grateful for a fix!

**Comment by zhou13** [comment]
You should not try to extract from it.
