### ISSUE TITLE
pretrained model do not exists on google drive???

### ISSUE THREAD

**Issue by guker** [zhou13/lcnn#77]
![image](https://github.com/user-attachments/assets/897113e0-741a-49a4-9fe5-8d555ba54846)

**Comment by zhou13** [comment]
Thanks for open the ticket. The university limited the Google Drive access and I am working on migrating to another online drive. Hopefully I can bring this online again this weekend.

**Comment by guker** [comment]
thanks for your reply！

**Comment by zhou13** [comment]
This should have been fixed in 175fb79.
